tenniscoach/custom_payment/urls.py
from django.urls import path
from .views import *

app_name = "custom_payment"

urlpatterns = [
    # Checkout per il pagamento
    path('checkout/<int:course_id>/', checkout, name='checkout')
]

tenniscoach/essential/urls.py
from django.urls import path, re_path
from .views import *

app_name = "essential"

urlpatterns = [

    # Home 
	re_path(r"^$|^\/$|^home\/$", tennis_home, name="home"),

    # Lista dei corsi
	path("courses/", CoursesListView.as_view(), name="courseslist"),

    # Dettagli di un corso
    path("course/<int:pk>/", CourseDetailView.as_view(), name="corso"),

    # Salvataggio di un corso
    path('save_course/<int:course_id>/', save_course, name='save_course'),
    
    # Corsi creati da un coach
    path('created_courses/', CreatedCoursesListView.as_view(), name = "createdcourses"),

    # Operazioni Create - Update - Delete su corsi e lezioni 
    path('create_lesson/<int:course_id>/', CreateLessonView.as_view(), name="createlesson"),
    path('create/', CreateCourseView.as_view(), name="createcorso"),

    path('edit_lesson/<int:pk>/', UpdateLessonView.as_view(), name="editlesson"),
    path('edit/<int:pk>/', UpdateCourseView.as_view(), name="editcorso"),

    path('delete_lesson/<int:pk>/', DeleteLessonView.as_view(), name="deletelesson"),
    path('delete/<int:pk>/', DeleteCourseView.as_view(), name="deletecorso"),

    # Endpoint per lista dei coach
    path('ajax/search/coaches/', ajax_search_coaches, name='ajax_search_coaches'),

] 

tenniscoach/tenniscoach/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #Profile urls
    path('profile/', include('users.urls')),

    #Core application urls
    path('', include('essential.urls')),
    
    #Block unauthorized access to media
    re_path(r'^media/.*$', authorize_media_resource),

    #Payment urls
    path('payment/', include('custom_payment.urls')),
    
    # User management related
    path("register/", UserCreateView.as_view(), name="register"),
    path("registerc/", CoachCreateView.as_view(), name="registerc"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    #Catch Errors
    path("not_authorized/", custom_403_view, name="403"),
    path("404/", custom_404_view, name='404'),
    re_path(r'^.*$', custom_404_view),
]

tenniscoach/users/urls.py
from django.urls import path, re_path
from .views import *

app_name = "users"

urlpatterns = [
    # Modifica del profilo
    path('change/', modify_profile, name='modifica_profilo'),

    # Profilo coach con corsi creati
    path('view/<int:pk>/', CoachProfileDetailView.as_view(), name='view_profile'),

    # Corsi acquistati
    path('dashboard/', YourCoursesListView.as_view(), name='dashboard'),

    # Cambio password
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),

    # Profilo utenti
    path("<int:pk>/", ProfileDetailView.as_view(), name="profile"),   
] 

tenniscoach/essential/forms.py
from django import forms
from .models import Course, Lesson
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator

import os

def validate_video(value):
    """
    Funzione di validazione per controllare che il file sia un video.
    """
    ext = os.path.splitext(value.name)[1]  # Ottieni l'estensione del file
    valid_extensions = ['.mp4']  # Estensioni di file video supportate
    if not ext.lower() in valid_extensions:
        raise ValidationError(_('Il file caricato non è un video valido. Carica un file con estensione .mp4'))

class CreateLessonForm(forms.ModelForm):
    
    video = forms.FileField(
        widget=forms.FileInput(attrs={'class': 'form-control'}),
        validators=[validate_video]
    )
    
    class Meta:
        model = Lesson
        fields = ['title', 'video']
        labels = {
            'title': 'Titolo',
            'video': 'Video'
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'video': forms.FileInput(attrs={'class': 'form-control'}),
        }

class CreateCorsoForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['title', 'description', 'picture', 'category', 'price']
        labels = {
            'title': 'Titolo',
            'description': 'Descrizione',
            'picture': 'Immagine',
            'category': 'Categoria',
            'price': 'Prezzo',
        }

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'picture': forms.FileInput(attrs={'class': 'form-control'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'}),
            'category': forms.Select(choices=(
                ('Principiante', 'Principiante'),
                ('Intermedio', 'Intermedio'),
                ('Esperto', 'Esperto'),
            ), attrs={'class': 'form-control'})
        }
        price = forms.DecimalField(
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
            validators=[MinValueValidator(0)]
        )

tenniscoach/essential/views.py
from typing import Any
from django.http.response import HttpResponseRedirect
from django.views.generic.list import ListView
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import AccessMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.http import Http404, HttpRequest, HttpResponse, JsonResponse
from custom_payment.models import Payment
# pipenv install django-braces
from braces.views import GroupRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from django.contrib.auth.models import User

from django.db.models import Q
from functools import reduce
import operator
from .models import *
from .forms import *
from users.models import Profile

#FBV che renderizza la home
def tennis_home(request):
    return render(request, template_name="home.html")

#CBV che mostra la lista dei corsi disponibili
class CoursesListView(ListView):
    title = "Corsi disponibili"
    model = Course
    template_name = "courses_list.html"
    paginate_by = 9

    def get_queryset(self):
        queryset = super().get_queryset()

        query = self.request.GET.get('query', '')

        # Trying to replicate full text search.
        single_terms = query.split()
        filter_gen = (Q(title__icontains=term) for term in single_terms)
        query_fulltext = reduce(operator.and_, filter_gen, Q())

        queryset = queryset.filter(query_fulltext)
        coach = self.request.GET.get('coach', '')
        level = self.request.GET.get('level','')
        ordering = self.request.GET.get('ordering','')
        order_by = self.request.GET.get('order_by','')
        paid = self.request.GET.get('paid', '')
        free = self.request.GET.get('free','')
        
        choices = {
            "Prezzo":"price",
            "Data": "date",
            "Titolo": "title",
            "Popolarità": "purchases_number"
        }

        if bool(paid) and not bool(free):
            queryset = queryset.filter(price__gt=0)
            
        elif bool(free) and not bool(paid):
            queryset = queryset.filter(price=0) 
        
        queryset = queryset.filter(user__user__username__icontains=coach)
        queryset = queryset.filter(category__icontains=level)
        
        try:
            if order_by:
                queryset = queryset.order_by(ordering+choices[order_by])
            else:
                queryset = queryset.order_by("-purchases_number")
        except:
            pass

        return queryset

    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["coaches"]=set()
        for user in User.objects.all():
            if user.groups.filter(name="Coach").exists():
                context["coaches"].add(user)
        
        context["ordinamenti"]=["Popolarità","Titolo", "Prezzo", "Data"]
        context["livelli"] = ["Principiante", "Intermedio", "Esperto"]
        return context


# View che invia risposte JSON, permettendo di cercare i coach a runtime con richieste AJAX
def ajax_search_coaches(request):
    term = request.GET.get('q', '')
    coaches = list()
    if term:
        for user in User.objects.filter(username__icontains=term):
            if user.groups.filter(name="Coach").exists():
                coaches.append(user)
    else:
        for user in User.objects.all():
            if user.groups.filter(name="Coach").exists():
                coaches.append(user)

    results = [{'id': coach.id, 'username': coach.username} for coach in coaches]
    #print(results)
    return JsonResponse(results, safe=False)

#CBV che mostra i dettagli di un singolo corso
class CourseDetailView(DetailView):
    model = Course
    template_name = "course.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["lessons"] = Lesson.objects.filter(course__pk=context["object"].pk)
        for coach in Profile.objects.all():
            if coach.pk == context["object"].user.pk:
                context["coach"] = coach

        user = self.request.user

        purchased=Purchase.objects.filter(course_id=context["object"].pk,user_id=user.id).exists()
        context["saved_by_current_user"] = purchased
        
        if purchased:
            context["purchase"] = Purchase.objects.get(user_id=user.id, course_id = context["object"].pk)

        if self.object.user_id == user.id:
            context["is_the_creator"] = True
        else:
            context["is_the_creator"] = False
        
        return context

#FBV per il salvataggio di un corso, dopo un eventuale pagamento
@login_required
def save_course(request, course_id):

    try:
        corso = get_object_or_404(Course, id=course_id)
    except Http404:
        return redirect("404")
    
    utente = request.user
    if (utente.id == corso.user_id):
        message = "Il corso è di tua proprietà!"
        messages.warning(request, message)
        return redirect("essential:createdcourses")
   
    purchased = Payment.objects.filter(description=course_id, billing_first_name = utente.username).exists()
    
    if corso.price > 0 and not purchased:
        message = "Azione non consentita"
        messages.success(request, message)
        
        return redirect("users:dashboard")

    # Verifica se l'utente ha già salvato questo corso
    _, created = Purchase.objects.get_or_create(user=utente.profile, course=corso, defaults={'date': timezone.now()})

    if created:
        message = "Corso salvato con successo!"
        messages.success(request, message)
    else:
        message = "Hai già salvato questo corso."
        messages.warning(request, message)
    
    
    return redirect("users:dashboard")



#Views solo per i coach

# Personalizzazione degli accessi alla viste
class GroupRequiredMixin(AccessMixin):
    group_required = None

    #Metodo che ...
    #   quando si crea/modifica/elimina un corso o crea una lezione restituisce:
    #   - TRUE  -> se l'id nel path corrisponde all'id di un corso creato dall'utente che fa la richiesta
    #   - TRUE  -> quando l'utente loggato è un admin
    #   - FALSE -> altrimenti
    #   quando si modifica/elimina una lezione restituisce:
    #   - TRUE  -> se l'id nel path corrisponde ad una lezione appartenente all'id di un corso creato dall'utente che fa la richiesta
    #   - TRUE  -> se non si passa un id
    #   - FALSE -> altrimenti
    def check(self):
        if "lesson" in self.request.path and "create_lesson" not in self.request.path :
            lesson_id = self.kwargs.get('pk')
            lesson = get_object_or_404(Lesson, id=lesson_id)
            return (lesson.course.user_id == self.request.user.id) or self.request.user.is_staff
        else:
            id = self.kwargs.get('course_id')
            if not id:
                id = self.kwargs.get('pk')
            if not id:
                return True
            course = get_object_or_404(Course, id=id)
            return (course.user_id == self.request.user.id) or self.request.user.is_staff

    #Se check restituisce False viene fatto il redirect alla pagina 403, altrimenti controllo il gruppo in group_required o admin, se non vi fanno parte -> "403"
    def dispatch(self, request, *args, **kwargs):
        if not self.check():
            return self.handle_no_permission()
        
        user_groups = request.user.groups.values_list('name', flat=True) #estrae i nomi dei gruppi ai quali appartiene l'utente corrente (request.user) e li memorizza in una lista
        if (not set(self.group_required).intersection(set(user_groups))) and not self.request.user.is_staff:
            return self.handle_no_permission()
        
        return super().dispatch(request, *args, **kwargs)
    
    def handle_no_permission(self) -> HttpResponseRedirect:
        return redirect('403')

#CBV per mostrare la lista dei corsi creati da un "Coach", per poterli modificare
class CreatedCoursesListView(GroupRequiredMixin, ListView):
    group_required = ["Coach"]
    template_name = "manage_courses.html"
    model = Course
    paginate_by = 9
    

    def get_queryset(self):
        queryset = super().get_queryset().filter(user_id = self.request.user.pk)
        order_by = self.request.GET.get('order_by', '')
        try:
            if order_by:
                queryset = queryset.order_by(order_by)
            else:
                queryset = queryset.order_by("-date")
        except:
            pass
        
        return queryset
    
#CBV per creare un corso, è necessario essere proprietari del corso o admin
class CreateCourseView(GroupRequiredMixin, CreateView):
    group_required = ["Coach"]
    form_class = CreateCorsoForm
    template_name = "create.html"
    success_url = reverse_lazy("essential:createdcourses")
    
    success_message = "Corso creato con successo!"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tipo'] = "corso"
        return context
    
    def form_valid(self, form):
        form.instance.user = self.request.user.profile  # Associa l'utente corrente come creatore del corso
        messages.success(self.request, self.success_message)
        return super().form_valid(form)
    
    def dispatch(self, request, *args, **kwargs):
        try:
            return super().dispatch(request, *args, **kwargs)
        except Http404:
            return redirect("404")
    
#CBV per creare una lezione, eredita dalla precendente. Viene cambiato il form e il messaggio
class CreateLessonView(CreateCourseView):
    form_class = CreateLessonForm
    success_message = "Lezione aggiunta con successo!"

    def get_success_url(self) -> str:

tenniscoach/essential/templates/course.html
{% extends 'base.html' %}
{% load static %}
{% load custom_filter %}
{% block title %} Dettagli di {{ object.title }} {% endblock %}

{% block content %}
<div id="toast-container">
         {% if messages %}
         {% for message in messages %}
         <div class="toast align-items-center text-bg-{{ message.tags|default:'info' }} border-0" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
               <div class="toast-body">
                  {{ message }}
               </div>
               <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
         </div>
         {% endfor %}
         {% endif %}
    </div>
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <!-- Pulsanti sopra il titolo del corso -->
                    <div>
                        {% if is_the_creator %}
                            <a href="{% url 'essential:createdcourses'%}" class="btn"> I tuoi corsi </a>
                        {% else %}
                            <a href="{% url 'users:dashboard'%}" class="btn"> I tuoi corsi </a>
                        {% endif %}
                        {% if user.is_superuser or is_the_creator %}
                        <div class="btn-group ml-2" role="group" aria-label="Pulsanti modifica e cancellazione">
                            <a href="{% url 'essential:editcorso' object.pk %}" class="btn btn-admin btn-creator">
                                <img src="{% static 'images/edit.png' %}" alt="Modifica" style="height: 20px; width: 20px;">
                            </a>
                            <a href="{% url 'essential:deletecorso' object.pk %}" class="btn btn-admin btn-creator">
                                <img src="{% static 'images/delete.png' %}" alt="Elimina" style="height: 20px; width: 20px;">
                            </a>
                        </div>
                        {%endif%}
                        {% if not saved_by_current_user and not is_the_creator %}
                            <!-- Mostra pulsanti solo se il corso non è stato salvato -->
                            {% if object.price != 0 %}
                                <form id="checkout-form" method="post" action="{% url 'custom_payment:checkout' object.pk %}">
                                    {% csrf_token %}
                                    <!-- Campo nascosto per l'id del corso -->
                                    <input type="hidden" name="course_id" value="{{ object.pk }}">
                                    <!-- Pulsante per inviare il form -->
                                    <button type="submit" class="btn btn-primary">Acquista</button>
                                </form>
                            {% else %}
                                <a href="{% url 'essential:save_course' object.pk %}" class="btn btn-primary">Salva</a>
                            {% endif %}
                        {% endif %}
                    </div>
                    <h5 class="mb-0 ">{{ object.title }}</h5>
                    <!-- Immagine del corso -->
                    <img src="/media{{ object.picture.url }}" alt="Immagine del corso" class="img-fluid rounded" style="max-width: 150px; margin-left:30px;">
                </div>
                <div class="card-body">
                    <!-- Dettagli del corso -->
                    <ul class="list-group list-group-flush body-lesson">
                        <li class="list-group-item"><strong>Descrizione:</strong> {{ object.description }}</li>
                        <li class="list-group-item"><strong>Livello:</strong> {{ object.category }}</li>
                        <li class="list-group-item"><strong>Prezzo:</strong> {% if object.isFree %}Gratis{% else %}{{ object.price }}€{% endif %}</li>
                        <li class="list-group-item"><strong>Acquistato:</strong> {{ object.purchases_number }} {% if object.purchases_number == 1 %} volta {% else %} volte {%endif%}</li>
                        <!-- Aggiungi altri campi del corso qui -->
                    </ul>
                </div>
                <!-- Lezioni come card -->
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-center mb-2">
                        <h6 class="card-title mb-0">Lezioni:</h6>
                        {% if user.is_superuser or is_the_creator %}
                        <a href="{% url 'essential:createlesson' object.pk %}" class="btn btn-admin btn-creator btn-rounded ml-2">
                            <img src="{% static 'images/add.png' %}" alt="Aggiungi" style="height: 20px; width: 20px;">
                        </a>
                        {% endif %}
                    </div>
                    {% for lesson in lessons %}
                        {% if user.is_authenticated and saved_by_current_user or is_the_creator %}
                        <!-- Mostra il link al modal solo se il corso è stato salvato -->
                        <a href="" class="text-decoration-none text-dark" data-bs-toggle="modal" data-bs-target="#videoModal{{ lesson.pk }}">
                        {% endif %}
                        <div class="card mb-2">
                            <div class="card-body d-flex justify-content-between align-items-center video-body">
                                <div class="d-flex flex-column">
                                    <span>{{ lesson.title }}</span>
                                    <span>{{ lesson.duration|format_timedelta }}</span>
                                </div>
                                <div >
                                    {% if user.is_superuser or is_the_creator %}
                                    <a href="{% url 'essential:editlesson' lesson.pk %}" class="btn btn-admin btn-creator btn-rounded">
                                        <img src="{% static 'images/edit.png' %}" alt="Modifica" style="height: 20px; width: 20px;">
                                    </a>
                                    <a href="{% url 'essential:deletelesson' lesson.pk %}" class="btn btn-admin btn-creator btn-rounded">
                                        <img src="{% static 'images/delete.png' %}" alt="Elimina" style="height: 20px; width: 20px;">
                                    </a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        {% if user.is_authenticated and saved_by_current_user or is_the_creator %}
                        </a>
                        {% endif %}
                        <!-- Modal per il video della lezione -->
                        <div class="modal fade" id="videoModal{{ lesson.pk }}" tabindex="-1" aria-labelledby="videoModalLabel{{ lesson.pk }}" aria-hidden="true">
                            <div class="modal-dialog modal-lg">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h5 class="modal-title" id="videoModalLabel{{ lesson.pk }}">{{ lesson.title }}</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <video controls controlsList="nodownload" class="w-100">
                                            <source src="/media/{{ lesson.video }}" type="video/mp4">
                                            Il tuo browser non supporta la visualizzazione di video.
                                        </video>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!-- Fine Modal -->
                    {% endfor %}
                    <div>
                    {% if saved_by_current_user %}
                    <p> <strong> Acquistato in data: </strong> {{purchase.date}} </p>
                    {% endif %}
                    </div>
                </div>

                <div class="card-footer d-flex justify-content-center align-items-center">
                    <!-- Testo dell'utente del coach -->
                    <div class="ml-3">
                        <a>Creato da:</a>
                        <a class="coach-profile" href="{% url 'users:view_profile' coach.pk %}"> {{ coach.user }}</a>
                        
                    </div>
                    <!-- Immagine profilo -->
                    <img src="/media{{ coach.picture.url }}" alt="Immagine profilo" class="rounded-circle mr-3" style="width: 50px; height: 50px; margin-right: 20px;">
                    <a> in data: {{object.date}}
                </div>
            </div>
        </div>
    </div>
</div>
<br>


<script>
     document.addEventListener('DOMContentLoaded', function() {
         var toastElList = [].slice.call(document.querySelectorAll('.toast'));
         var toastList = toastElList.map(function(toastEl) {
             return new bootstrap.Toast(toastEl, { autohide: true, delay: 4000 });
         });
         toastList.forEach(toast => toast.show());
     });
</script>
{% endblock %}

tenniscoach/essential/templates/course_card.html
<div class="card shadow-sm card-custom" data-toggle="tooltip" data-placement="top" title="{{c.description}}">
    <img src="/media{{ c.picture.url }}" alt="Immagine Profilo" class="img-fluid rounded-start img-course">
    <div class="card-body">
        <p class="card-text">{{c.title|truncatechars:45}}</p>
        <div class="d-flex justify-content-between">
            <p class="card-text">{{c.category}}</p>
            <p class="card-text">Acquistato: {{ c.purchases_number }} {% if c.purchases_number == 1 %} volta {% else %} volte {%endif%}</p>
        </div>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <a type="button" class="btn btn-sm btn-outline-secondary" href="{% url 'essential:corso' c.pk %}">Vedi</a>
            </div>
            {% if c.isFree %}
                <h6 class="card-text">Gratis</h6>
            {% else %}                        
                <h6 class="card-text">{{c.price}}€</h6>
            {% endif %}
            <h6 class="text-muted">Coach: {{c.user.user}}</h6>
        </div>
    </div>
</div>

tenniscoach/essential/templates/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Creazione {{tipo}} {% endblock %}

{% block content %}
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h2 class="mb-0">Creazione {{tipo}} </h2>
                </div>
                <div class="card-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        
                        <!-- Form principale (CourseForm) -->
                        
                        {{form | crispy}}
                        {% if tipo == "lezione" %}
                            <a type="button" class="btn btn-secondary" href="{% url 'essential:corso' course_id %}" >Indietro</a>
                        {% else %}
                            <a type="button" class="btn btn-secondary" href="{% url 'essential:createdcourses' %}" >Indietro</a>
                        {% endif %}
                        <button type="submit" class="btn btn-primary">Crea</button>
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

tenniscoach/essential/templates/home.html
{% extends 'base.html' %}


{% load static %}
<link rel="stylesheet" type="text/css"  href= "{% static 'css/style.css' %}">



{% block content %} 

<div id="myCarousel" class="carousel slide mb-6 border-warning" data-bs-ride="carousel" data-bs-interval="4000" style="width:100%;">
    <div class="carousel-inner rounded-1 shadow-4-strong">
      <div id="carousel" class="carousel-item active" >
        <img src="{% static '/images/background1.jpg' %}" class="d-block w-100" />
        <div class="container">
          <div class="carousel-caption text-start">
          {% if user.is_authenticated %}
            <h1>Benvenuto {{user.username}}!</h1>
            <p>Clicca per visualizzare i tuoi corsi!</p>
            <p><a class="btn" href="{% url 'users:dashboard'%}"><span>I tuoi corsi</span></a></p>
            {% else %}
            <h1>“Tu non sai cos'è il tennis, è una relazione.”</h1>
            <p class="opacity-75">ZENDAYA - Tashi Donaldson</p>
            <p><a class="btn" href="{% url 'essential:courseslist' %}"><span>Lista corsi</span></a></p>
            {% endif %}
          </div>
        </div>
      </div>
      <div id="carousel" class="carousel-item">
        <img src="{% static '/images/background2.jpg' %}" class="d-block w-100"  />
        <div class="container">
          <div class="carousel-caption"> 
            {% if user.is_authenticated %}
            <h1>Accedi al tuo profilo!</h1>
            <p>Per modificare i tuoi dati</p>
            <p><a class="btn" href="{% url 'users:profile' user.pk %}"><span>Profilo</span></a></p>
            {% else %}
            <h1>Unisciti ai nostri corsi di tennis online!</h1>
            <p>Visita il sito e inizia a migliorare il tuo gioco oggi stesso!</p>
            <p><a class="btn" href="{% url 'register' %}"><span>Sign Up</span></a></p>
            {% endif %}
          </div>
        </div>
      </div>
      <div id="carousel" class="carousel-item" >
        
        <img src="{% static '/images/background3.jpg' %}" class="d-block w-100" />
        <div class="container">
          <div class="carousel-caption text-end">
          {% if user.is_authenticated %}
            <h1>“Tu non sai cos'è il tennis,</h1>
            <h1> è una relazione.”</h1>
            <p class="opacity-75">ZENDAYA - Tashi Donaldson</p>
            <p><a class="btn" href="{% url 'essential:courseslist' %}"><span>Lista corsi</span></a></p>

            {% else %}
            <h1>Accedi al profilo</h1>
            <p>... e continua il percorso coi nostri corsi!</p>
            <p><a class="btn" href="{% url 'login' %}"><span>Log In</span></a></p>
            {%endif%}
          </div>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>

{% endblock %}