tenniscoach/essential/urls.py
from django.urls import path, re_path
from .views import *

app_name = "essential"

urlpatterns = [

    # Home 
	re_path(r"^$|^\/$|^home\/$", tennis_home, name="home"),

    # Lista dei corsi
	path("courses/", CoursesListView.as_view(), name="courseslist"),

    # Dettagli di un corso
    path("course/<int:pk>/", CourseDetailView.as_view(), name="corso"),

    # Salvataggio di un corso
    path('save_course/<int:course_id>/', save_course, name='save_course'),
    
    # Corsi creati da un coach
    path('created_courses/', CreatedCoursesListView.as_view(), name = "createdcourses"),

    # Operazioni Create - Update - Delete su corsi e lezioni 
    path('create_lesson/<int:course_id>/', CreateLessonView.as_view(), name="createlesson"),
    path('create/', CreateCourseView.as_view(), name="createcorso"),

    path('edit_lesson/<int:pk>/', UpdateLessonView.as_view(), name="editlesson"),
    path('edit/<int:pk>/', UpdateCourseView.as_view(), name="editcorso"),

    path('delete_lesson/<int:pk>/', DeleteLessonView.as_view(), name="deletelesson"),
    path('delete/<int:pk>/', DeleteCourseView.as_view(), name="deletecorso"),

    # Endpoint per lista dei coach
    path('ajax/search/coaches/', ajax_search_coaches, name='ajax_search_coaches'),

] 

tenniscoach/tenniscoach/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #Profile urls
    path('profile/', include('users.urls')),

    #Core application urls
    path('', include('essential.urls')),
    
    #Block unauthorized access to media
    re_path(r'^media/.*$', authorize_media_resource),

    #Payment urls
    path('payment/', include('custom_payment.urls')),
    
    # User management related
    path("register/", UserCreateView.as_view(), name="register"),
    path("registerc/", CoachCreateView.as_view(), name="registerc"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    #Catch Errors
    path("not_authorized/", custom_403_view, name="403"),
    path("404/", custom_404_view, name='404'),
    re_path(r'^.*$', custom_404_view),
]

tenniscoach/users/urls.py
from django.urls import path, re_path
from .views import *

app_name = "users"

urlpatterns = [
    # Modifica del profilo
    path('change/', modify_profile, name='modifica_profilo'),

    # Profilo coach con corsi creati
    path('view/<int:pk>/', CoachProfileDetailView.as_view(), name='view_profile'),

    # Corsi acquistati
    path('dashboard/', YourCoursesListView.as_view(), name='dashboard'),

    # Cambio password
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),

    # Profilo utenti
    path("<int:pk>/", ProfileDetailView.as_view(), name="profile"),   
] 

tenniscoach/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
  
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css"> 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> 

<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

  {% load static%} 
  <link rel="shortcut icon" href="{% static '/images/favicon.ico' %}">


  
  <link rel="stylesheet" type="text/css"  href= "{% static 'css/style.css' %}">

  {% load crispy_forms_tags %} 
  

  {% block header%} 
  
  {% endblock %}

</head>


<title>{% block title %}Tennis Coach {% endblock %}</title> 

{% if user.is_authenticated and "ok" in request.GET.login %}
  <div id="info" class="modal fade" tabindex="-1" role="dialog" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog border border-warning  border-2 rounded-2" role="document" >
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Benvenuto {{ user.username }}</h5>
        </div>
        <div class="modal-body">
          <p>La procedura di login è andata a buon fine.</p>
        </div>
      </div>
    </div>
  </div>
  <script>
    $(document).ready(function(){
        var myModal = new bootstrap.Modal(document.getElementById('info'));
        myModal.show();
    });
  </script>
{% endif %}


<body class="body body-tennis">

  <nav class="navbar navbar-expand-lg  navbar-dark " style="background-color: #000000;">
  {% block navbar %}
    <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand d-flex align-items-center" href="{% url 'essential:home' %}">
      <img src="{% static '/images/logo.png' %}" alt="Logo" width="80" height="60" class="me-2">
      TennisCoach
    </a>
    <div class="collapse navbar-collapse" >
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'essential:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'essential:courseslist' %}">Cerca corsi</a>
        </li>
        {% if "Coach" in user.groups.all.0.name or user.is_staff%}
          <li class="nav-item"><a class="nav-link" href="{% url 'essential:createcorso' %}">Aggiungi corso</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'essential:createdcourses' %}">Gestisci corsi</a></li>
        {% endif %}
      </ul>
      {% if user.is_authenticated %}
        <form id="logout-form" method="post" action="{% url 'logout' %}" >
          {% csrf_token %}
          <button type="submit" class="btn">Logout</button>
        </form>
        <div class="dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="/media{{ user.profile.picture.url }}" alt="Immagine Profilo" width="50" height="50" class="rounded-circle">
          </a>
          <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="dropdownUser1">
            <li><a class="dropdown-item text-end" href="{% url 'users:dashboard'%}">Corsi acquistati</a></li>
            <li><a class="dropdown-item text-end" href="{% url 'users:profile' user.profile.pk %}">Modifica profilo</a></li>
          </ul>
        </div>

      {% else %}
      <form class="d-flex" role="search">
        <a class="btn" href="{% url 'register' %}"><span>Sign Up</span></a>
        <a class="btn" href="{% url 'login' %}"><span>Log In</span></a>

         </form>
      {% endif %}
     
    </div>
  </div>
  {% endblock %}
</nav>


{% block content %}
{% endblock  %}
  

   <div class="container">
    <footer class="py-3 my-4">
      <div class="row justify-content-center mb-3">
        <div class="col-auto">
          <a class="btn btn-admin" href="/admin/"><span>Admin</span></a>
        </div>
        {% if user.is_staff %}
        <div class="col-auto">
          <a class="btn btn-admin" href="{% url 'registerc' %}">Sign up Coach</a>
        </div>
        {% endif %}
      </div>
      <ul class="nav justify-content-center border-bottom pb-3 mb-3">
        <p class="text-center custom-footer">Progetto di Tecnologie Web - 2024</p>
      </ul>
      <p class="text-center custom-footer">© Luca Lodesani 165507</p>
    </footer>
  </div>
  
  </body>
  </html>

tenniscoach/templates/user_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %} 

{% block title %} Creazione Utente {{ group }} {% endblock %} 


 {% block content%}
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h3 class="mb-0">Pagina di Registrazione {{ group }}</h3>
                </div>
                <div class="card-body">
                
                    <p>Si prega di compilare i campi necessari</p>
                    <form method="post"> {% csrf_token %}

                    {{form | crispy}}
                    
                    <input type="submit" class="btn btn-success" value="Registrati">
                    
                    </form>

                </div>

            </div>
        </div>
    </div>
</div>

{% endblock %}