tenniscoach/tenniscoach/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #Profile urls
    path('profile/', include('users.urls')),

    #Core application urls
    path('', include('essential.urls')),
    
    #Block unauthorized access to media
    re_path(r'^media/.*$', authorize_media_resource),

    #Payment urls
    path('payment/', include('custom_payment.urls')),
    
    # User management related
    path("register/", UserCreateView.as_view(), name="register"),
    path("registerc/", CoachCreateView.as_view(), name="registerc"),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    #Catch Errors
    path("not_authorized/", custom_403_view, name="403"),
    path("404/", custom_404_view, name='404'),
    re_path(r'^.*$', custom_404_view),
]

tenniscoach/users/urls.py
from django.urls import path, re_path
from .views import *

app_name = "users"

urlpatterns = [
    # Modifica del profilo
    path('change/', modify_profile, name='modifica_profilo'),

    # Profilo coach con corsi creati
    path('view/<int:pk>/', CoachProfileDetailView.as_view(), name='view_profile'),

    # Corsi acquistati
    path('dashboard/', YourCoursesListView.as_view(), name='dashboard'),

    # Cambio password
    path('change-password/', ChangePasswordView.as_view(), name='change_password'),

    # Profilo utenti
    path("<int:pk>/", ProfileDetailView.as_view(), name="profile"),   
] 

tenniscoach/users/models.py
from django.db import models
import os
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, *args, **kwargs):
  if created:
    Profile.objects.create(user=instance)

class Profile(models.Model):
    """
    Entity that models a profile.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=20, null=True)
    surname = models.CharField(max_length=20, null=True)
    email = models.EmailField(null = True)
    description = models.CharField(max_length=400, null=True, blank=True)
    picture = models.ImageField(
        upload_to='static/users_pics',
        default='/static/images/unknown_user.jpg',
        blank=True
    )
    purchases = models.ManyToManyField(to = "essential.Course", through="essential.Purchase", blank=True, related_name="profile_purchases")


    def __str__(self):
      return f"{self.user}: {self.name} {self.surname} ({self.email})"

    class Meta:
        verbose_name_plural = "Profili utente"


    def has_permession_auth(self, resource:str):
      #L'import va fatto dentro in modo che sia lazy; così facendo quando richiamo has_permession_auth Lesson sarà definita
      from essential.models import Lesson
      lesson = Lesson.objects.filter(video__icontains=resource)
      if not lesson:
        return False
      
      # Tra tutti i corsi che contengono la risorsa controllo se ce n'è almeno uno che è acquistato
      if lesson.filter(course__pk__in=self.purchases.values('pk')):
        return True
      
      if lesson.filter(course__user_id=self.user.id):
        return True
      return False

tenniscoach/users/forms.py
from django import forms
from .models import Profile
from django.core.exceptions import ValidationError

# Validator per assicurarsi che il nome sia in un formato consono
def validate_name(value):
    parts = value.split()
    for part in parts:
        if not part.isalpha():
            raise ValidationError('Il nome deve contenere solo lettere.')

# Validator per assicurarsi che il cognome sia in un formato consono
def validate_surname(value):
    parts = value.split()
    for part in parts:
        if not part.isalpha():
                raise ValidationError('Il cognome deve contenere solo lettere.')


class OptionalFieldsMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for _, field in self.fields.items():
            field.required = False

class UserProfileForm(OptionalFieldsMixin, forms.ModelForm):
    name = forms.CharField(
        max_length=20,
        validators=[validate_name],
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    surname = forms.CharField(
        max_length=20,
        validators=[validate_surname],
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )

    class Meta:
        model = Profile
        fields = ['name', 'surname','description', 'email', 'picture']
        labels = {
            'name': 'Nome',
            'surname': 'Cognome',
            'description': 'Descrizione',
            'email': 'Indirizzo email',
            'picture': 'Immagine del profilo',
        }
        widgets ={
            'description': forms.Textarea(attrs={'cols': 80, 'rows': 3}),
            'picture': forms.FileInput(attrs={'class': 'form-control'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'picture' in self.fields:
            self.fields['picture'].widget.attrs.pop('clear', None)

tenniscoach/users/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from .models import *
from django.views.generic.detail import DetailView
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.views import PasswordChangeView
from django.urls import reverse_lazy
from django.contrib.auth.models import Group
from django.contrib import messages
from django.core.paginator import Paginator

from essential.models import *
# Create your views here.

#CBV che mostra il profilo dell'utente loggato
class ProfileDetailView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = "profile.html"

    def dispatch(self, request, *args, **kwargs):
        # Ottieni l'ID utente dall'URL
        
        profile_id = int(self.kwargs['pk'])

        #Verifica che tale profilo esista, altrimenti 404
        try:
            _ = get_object_or_404(Profile, pk=profile_id)
        except Http404:
            return redirect("404")

        # Verifica se l'ID utente corrisponde a quello dell'utente loggato
        if profile_id != self.request.user.id and not self.request.user.is_staff:
            # Se non corrisponde, restituisci una risposta 403
            return redirect("403")
        return super().dispatch(request, *args, **kwargs)

#FBV che permette di aggiornare il proprio profilo
@login_required
def modify_profile(request):
    profile = request.user.profile
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            # Salvataggio dei dati nel database
            
            messages.success(request, "Profilo modificato con successo!")
            form.save()
            return redirect('users:profile', profile.pk)  # Reindirizza a una vista successiva
    else:
        form = UserProfileForm(instance=profile)
    
    return render(request, 'edit_profile.html', {'form': form})

#CBV che mostra una pagina profilo di un coach con i relativi corsi messi a disposizione
class CoachProfileDetailView(DetailView):
    model = Profile
    template_name = "presentation.html"
    
    def dispatch(self, request, *args, **kwargs):
        try:
            self.object = self.get_object()
            coach_group = Group.objects.get(name='Coach')
            
            # Verifica se l'utente associato al profilo è un coach
            if not (self.object.user.groups.filter(name=coach_group.name).exists() or self.object.user.is_staff):
                return redirect("403")
            return super().dispatch(request, *args, **kwargs)
        except Http404:
            return redirect("404")
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        order_by = self.request.GET.get('order_by', '')
        
        courses = Course.objects.filter(user_id = self.object.id)
        try:
            if order_by:
                courses = courses.order_by(order_by)
            else:
                courses = courses.order_by("-purchases_number")
        except:
            pass

        paginator = Paginator(courses, 6)  # 6 corsi per pagina
        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context['page_obj'] = page_obj
        context['full_name'] = f"{self.object.name} {self.object.surname}" if self.object.name and self.object.surname else None
        return context
    
#CBV che permette di visualizzare l'elenco dei corsi acquistati dall'utente
class YourCoursesListView(LoginRequiredMixin, ListView):
    model = Profile
    template_name = "dashboard.html"
    
    paginate_by = 6

    def get_queryset(self):
        queryset =  self.request.user.profile.purchases.all()
        order_by = self.request.GET.get('order_by', '')
        if order_by:
            queryset = queryset.order_by(order_by)
        else:
            queryset = queryset.order_by("-purchase__date")
        
        return queryset

#CBV che gestisce il cambiamento della password per l'utente loggato
class ChangePasswordView(LoginRequiredMixin, PasswordChangeView):
    form_class = PasswordChangeForm
    template_name = 'change_password.html'
    success_message = "Password modificata con successo!"

    def form_valid(self, form):
        # Aggiungi il messaggio di successo
        messages.success(self.request, self.success_message)
        return super().form_valid(form)
    
    def get_success_url(self):
        # Costruisci l'URL di successo con l'ID dell'utente
        return reverse_lazy('users:profile', kwargs={'pk': self.request.user.id})

tenniscoach/users/templates/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Cambia Password {% endblock %}

{% block content %}
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h2 class="mb-0">Modifica della password </h2>
                </div>
                <div class="card-body">
                    <form id="modificaForm" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    </form>
                </div>
                <div class="card-footer">
                    <!-- Pulsante Modifica -->
                    <a type="button" class="btn btn-secondary" href="{% url 'users:profile' user.pk%}" >Indietro</a>
                    <button type="submit" form="modificaForm" class="btn btn-primary" id="salvaBtn">Salva</button>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

tenniscoach/users/templates/dashboard.html
{% extends 'base.html' %}
{% block title %} I tuoi corsi {% endblock %}

{% block content %}

<div class="album py-5 ">
    <div id="toast-container">
         {% if messages %}
         {% for message in messages %}
         <div class="toast align-items-center text-bg-{{ message.tags|default:'info' }} border-0" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
               <div class="toast-body">
                  {{ message }}
               </div>
               <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
         </div>
         {% endfor %}
         {% endif %}
    </div>
    <div class="container">
        <h2 class="n_text"><strong> I tuoi corsi acquistati... </strong></h2>
        <br>
        <div class="d-flex align-items-center mb-4">
            <p class="mr-2 n_text" style="margin: 5px;">Ordina per:</p>
            <form method="get" class="form-inline d-flex align-items-center flex-nowrap">
                <select name="order_by" class="form-control mr-2" style="margin: 5px;">
                    <option value="">Seleziona...</option>
                    <option value="-purchases_number">Popolarità(decrescente)</option>
                    <option value="purchases_number">Popolarità(crescente)</option>
                    <option value="title">Nome (A-Z)</option>
                    <option value="-title">Nome (Z-A)</option>
                    <option value="price">Prezzo (crescente)</option>
                    <option value="-price">Prezzo (decrescente)</option>
                    <option value="purchase__date">Data d'acquisto(crescente)</option>
                    <option value="-purchase__date">Data d'acquisto(decrescente)</option>
                </select>
                <button type="submit" class="btn btn-search btn-primary" style="margin: 5px;">Ordina</button>
            </form>
        </div>

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% if object_list %}
            {% for c in object_list %}
            <div class="col">
                {% include "course_card.html" %}
            </div>
            {% endfor %}
            {% else %}
            <p class = "n_text"> Nessun corso acquistato </p>
            {%endif%}
        </div>
        
        <br>
        <div class="n_text"> {{ page_obj.paginator.count }} risultati trovati | Pagina {{page_obj.number}} </div>
        <ul class="pagination mt-2 mb-0 justify-content-center n_text">
            <li class="page-item">
                {% if page_obj.has_previous %}
                    <a class='btn' href="?{% if request.GET.query %}query={{ request.GET.query }}{% endif %}{% if request.GET.coach %}&coach={{ request.GET.coach }}{% endif %}{% if request.GET.paid %}&paid={{ request.GET.paid }}{% endif %}{% if request.GET.free %}&free={{ request.GET.free }}{% endif %}{% if request.GET.level %}&level={{ request.GET.level }}{% endif %}{% if request.GET.ordering %}&ordering={{ request.GET.ordering }}{% endif %}{% if request.GET.order_by %}&order_by={{ request.GET.order_by }}{% endif %}&page={{ page_obj.previous_page_number }}"><</a>
                {% endif %}
            </li>
            <li class="page-item">
                {% if page_obj.has_next %}
                    <a class='btn' href="?{% if request.GET.query %}query={{ request.GET.query }}{% endif %}{% if request.GET.coach %}&coach={{ request.GET.coach }}{% endif %}{% if request.GET.paid %}&paid={{ request.GET.paid }}{% endif %}{% if request.GET.free %}&free={{ request.GET.free }}{% endif %}{% if request.GET.level %}&level={{ request.GET.level }}{% endif %}{% if request.GET.ordering %}&ordering={{ request.GET.ordering }}{% endif %}{% if request.GET.order_by %}&order_by={{ request.GET.order_by }}{% endif %}&page={{ page_obj.next_page_number }}">></a>
                {% endif %}
            </li>
        </ul>
        </div>
</div>
<script>
     document.addEventListener('DOMContentLoaded', function() {
         var toastElList = [].slice.call(document.querySelectorAll('.toast'));
         var toastList = toastElList.map(function(toastEl) {
             return new bootstrap.Toast(toastEl, { autohide: true, delay: 4000 });
         });
         toastList.forEach(toast => toast.show());
     });
</script>
{% endblock %}

tenniscoach/users/templates/edit_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Profilo {% endblock %}

{% block content %}
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h2 class="mb-0">Modifica Profilo: </h2>
                </div>
                <div class="card-body">
                    <form id="modificaForm" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form | crispy }}
                    </form>
                    <a href="{% url 'users:change_password' %}">Vuoi cambiare la password? Clicca qui</a>
                </div>
                <div class="card-footer">
                    <!-- Pulsante Modifica -->
                    <a type="button" class="btn btn-secondary" href="{% url 'users:profile' user.pk%}" >Indietro</a>
                    <button type="submit" form="modificaForm" class="btn btn-primary" id="salvaBtn">Salva</button>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

tenniscoach/users/templates/presentation.html
{% extends 'base.html' %}

{% block title %}Profilo Coach{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="row g-0">
                    <div class="col-md-4 text-center p-3">
                        <img src="/media{{ object.picture.url }}" alt="Profile Picture" class="img-fluid rounded-circle" style="width: 150px; height: 150px; object-fit: cover;">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            {% if full_name %}
                                <h2 class="card-title">{{ full_name }}</h2>
                                <h5 class="card-title">Username: {{ object.user }}</h5>

                            {% else %}
                                <h2 class="card-title">Username: {{ object.user }}</h2>
                            {% endif %}
                            
                            <p class="card-text"><strong>Email:</strong>{% if  object.email  %} {{ object.email }} {% else %} Non disponibile {% endif %}</p>
                            <p class="card-text"><strong>Descrizione:</strong>{% if  object.description  %} {{ object.description }} {% else %} Non disponibile {% endif %}</p>
                            <!-- Aggiungi ulteriori informazioni se necessario -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-4">
    <h2 class="n_text"><strong> I suoi corsi... </strong></h2>
    <br>
    <div class="d-flex align-items-center mb-4">
        <p class="mr-2 n_text" style="margin: 5px;">Ordina per:</p>
        <form method="get" class="form-inline d-flex align-items-center flex-nowrap">
            <select name="order_by" class="form-control mr-2" style="margin: 5px;">
                <option value="">Seleziona...</option>
                <option value="-purchases_number">Popolarità(decrescente)</option>
                <option value="purchases_number">Popolarità(crescente)</option>
                <option value="title">Nome (A-Z)</option>
                <option value="-title">Nome (Z-A)</option>
                <option value="price">Prezzo (crescente)</option>
                <option value="-price">Prezzo (decrescente)</option>
            </select>
            <button type="submit" class="btn btn-search btn-primary" style="margin: 5px;">Ordina</button>
        </form>
    </div>

    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for c in page_obj %}
        <div class="col">
            {% include 'course_card.html' %}
        </div>
        {% endfor %}
    </div>
    
    <br>
    <div class="n_text"> {{ page_obj.paginator.count }} risultati trovati | Pagina {{ page_obj.number }} </div>
    <ul class="pagination mt-2 mb-0 justify-content-center n_text">
        <li class="page-item">
            {% if page_obj.has_previous %}
                <a class="btn" href="?{% if request.GET.query %}query={{ request.GET.query }}{% endif %}{% if request.GET.coach %}&coach={{ request.GET.coach }}{% endif %}{% if request.GET.paid %}&paid={{ request.GET.paid }}{% endif %}{% if request.GET.free %}&free={{ request.GET.free }}{% endif %}{% if request.GET.level %}&level={{ request.GET.level }}{% endif %}{% if request.GET.ordering %}&ordering={{ request.GET.ordering }}{% endif %}{% if request.GET.order_by %}&order_by={{ request.GET.order_by }}{% endif %}&page={{ page_obj.previous_page_number }}">«</a>
            {% endif %}
        </li>
        <li class="page-item">
            {% if page_obj.has_next %}
                <a class="btn" href="?{% if request.GET.query %}query={{ request.GET.query }}{% endif %}{% if request.GET.coach %}&coach={{ request.GET.coach }}{% endif %}{% if request.GET.paid %}&paid={{ request.GET.paid }}{% endif %}{% if request.GET.free %}&free={{ request.GET.free }}{% endif %}{% if request.GET.level %}&level={{ request.GET.level }}{% endif %}{% if request.GET.ordering %}&ordering={{ request.GET.ordering }}{% endif %}{% if request.GET.order_by %}&order_by={{ request.GET.order_by }}{% endif %}&page={{ page_obj.next_page_number }}">»</a>
            {% endif %}
        </li>
    </ul>
</div>
{% endblock %}

tenniscoach/users/templates/profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %} Profilo {% endblock %}

{% block content %}
<div id="toast-container">
         {% if messages %}
         {% for message in messages %}
         <div class="toast align-items-center text-bg-{{ message.tags|default:'info' }} border-0" role="alert" aria-live="assertive" aria-atomic="true">
            <div class="d-flex">
               <div class="toast-body">
                  {{ message }}
               </div>
               <button type="button" class="btn-close btn-close-white me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
            </div>
         </div>
         {% endfor %}
         {% endif %}
    </div>
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h5 class="mb-0">Username: {{ object.user.username }}</h5>
                    <!-- Immagine del corso -->
                    <img src="/media{{ object.picture.url }}" alt="Immagine del profilo" class="img-fluid rounded" style="max-width: 120px;">
                </div>
                <div class="card-body">
                    <!-- Dettagli del corso -->
                    <ul class="list-group list-group-flush body-lesson">
                        <li class="list-group-item"><strong>Nome:</strong> {% if object.name %}{{ object.name }}{% endif %}</li>
                        <li class="list-group-item"><strong>Cognome:</strong> {% if object.surname %}{{ object.surname }}{% endif %}</li>
                        <li class="list-group-item"><strong>Descrizione:</strong> {% if object.description %}{{ object.description }}{% endif %}</li>
                        <li class="list-group-item"><strong>Email:</strong> {% if object.email %}{{ object.email }}{% endif %}</li>
                    </ul>
                </div>
                <div class="card-body">
                    <!-- Pulsante Modifica -->
                    {%if user.pk == object.pk %}
                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:modifica_profilo' %}">
                            Modifica
                        </a>
                    {%endif%}
                </div>
            </div>
        </div>
    </div>
</div>
<script>
     document.addEventListener('DOMContentLoaded', function() {
         var toastElList = [].slice.call(document.querySelectorAll('.toast'));
         var toastList = toastElList.map(function(toastEl) {
             return new bootstrap.Toast(toastEl, { autohide: true, delay: 4000 });
         });
         toastList.forEach(toast => toast.show());
     });
</script>

{% endblock %}